Fix Test Suite
Some race in Kafka due to using the same tx-id in each test after
deleting/creating the topic.

>org.apache.kafka.common.errors.UnknownProducerIdException: This exception is raised by the broker if it could not locate the producer metadata associated with the producerId in question. This could happen if, for instance, the producer's records were deleted because their retention time had elapsed. Once the last records of the producerId are removed, the producer's metadata is removed from the broker, and future appends by the producer will return this exception.

Now the suite runs in STS, still errors running from maven.